brand:
  name: <img src="/assets/img/logos/kibioctet.png" class="logo-header" />
menu-string: Menu

nav:
  - title: Nos Services
    url: '/#services'
  - title: Nos Valeurs
    url: '/#about'
  - title: Équipe
    url: '/#team'
  - title: Contact
    url: '/#contact'

copyright: © 2018

social-buttons:

quicklinks:
  - title: CGU
    url: '/cgu/'

modal:
  date-string: 'Date: '
  client-string: 'Client: '
  category-string: 'Category: '
  close-icon: 'fa fa-times'
close-string: 'Close Project'
